apiVersion: v1
kind: Pod
metadata: 
  name: pod2
  labels: 
    type: myapp
spec:
  containers:
    - name: try1
      image: ditissproject2024/try1

---

apiVersion: v1
kind: Service
metadata: 
  name: myservice
spec:
  type: NodePort
  selector:
    type: myapp
  ports:
    - protocol: TCP 
      port: 80
      targetPort: 8080
